# Generated by Django 2.0.2 on 2018-12-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compress',
            new_name='Img',
        ),
    ]
