# Generated by Django 2.0.2 on 2018-12-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0002_auto_20181201_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='Image',
        ),
    ]
