# Generated by Django 2.0.2 on 2018-12-02 13:30

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0003_auto_20181202_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=smartfields.fields.ImageField(upload_to='images/'),
        ),
    ]
