# Generated by Django 2.0.2 on 2018-12-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0011_auto_20181203_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Compress',
        ),
    ]
